xssp_api/frontend/dashboard/forms.py
import re

from xssp_api import default_settings as settings
from flask_wtf import FlaskForm
from wtforms.fields import FileField, SelectField, TextAreaField, StringField, SubmitField, EmailField
from wtforms import validators

from xssp_api.frontend.validators import (FileExtension, NAminoAcids,
                                          English, NoSpam,
                                          OnlyRequiredIf, PdbidExists, OnlyAllowedIf)


RE_PDB_ID = re.compile(r"^[0-9a-zA-Z]{4}$")


class XsspForm(FlaskForm):

    input_type = SelectField(u'Input', default="pdb_id",
                             choices=[('pdb_id', 'PDB code'),
                                      ('pdb_redo_id', 'PDB_REDO code'),
                                      ('pdb_file', 'PDB file'),
                                      ('sequence', 'Sequence')])
    output_type = SelectField(u'Output', default="dssp",
                              choices=[('dssp', 'classic DSSP'),
                                       ('mmcif', 'DSSP-annotated mmCIF'),
                                       ('hssp_hssp', 'HSSP'),
                                       ('hssp_stockholm', 'HSSP (Stockholm)'),
                                       ('hg_hssp', 'HSSP (Human Genome)')],
                              validators=[OnlyAllowedIf('mmcif', 'input_type', ['pdb_file'])])
    pdb_id = StringField(u'PDB code', validators=[OnlyRequiredIf('input_type', ['pdb_id', 'pdb_redo_id']),
                                                  validators.Regexp(regex=RE_PDB_ID),
                                                  PdbidExists(settings.PDB_ROOT, settings.PDB_REDO_ROOT)])
    sequence = TextAreaField(u'Sequence', validators=[
        OnlyRequiredIf('input_type', ['sequence']),
        NAminoAcids(min=25)
    ])
    file_ = FileField(u'File', validators=[OnlyRequiredIf('input_type', ['pdb_file'])])

    def __init__(self, allowed_extensions=None, **kwargs):
        super(XsspForm, self).__init__(**kwargs)
        if allowed_extensions:
            file_field = self._fields.get('file_')
            file_field.validators.append(FileExtension(allowed_extensions))


class SupportForm(FlaskForm):
    email = EmailField('Email',
                       [validators.DataRequired(), validators.Email()])
    body = TextAreaField('Body', [validators.DataRequired(),
                                  validators.Regexp('^.*[A-Za-z].*$', flags=re.MULTILINE, message="Please fill in a text message here."),
                                  English(), NoSpam()])

xssp_api/frontend/dashboard/views.py
import logging
import traceback

from flask import (Blueprint, current_app as app, g, redirect, render_template,
                   request, url_for)

from xssp_api import get_version
from xssp_api.frontend.dashboard.forms import XsspForm
from xssp_api.frontend.dashboard.forms import SupportForm
from xssp_api.services.xssp import process_request
from xssp_api.services.mail import mail

_log = logging.getLogger(__name__)

bp = Blueprint('dashboard', __name__)


@bp.route("/", methods=['GET', 'POST'])
def index():
    _log.debug("request for index")
    form = XsspForm(allowed_extensions=app.config['ALLOWED_EXTENSIONS'])
    if form.validate_on_submit():
        celery_id = process_request(form.input_type.data, form.output_type.data,
                                    form.pdb_id.data, request.files,
                                    form.sequence.data)

        _log.info("Redirecting to output page")
        return redirect(url_for('dashboard.output',
                                input_type=form.input_type.data,
                                output_type=form.output_type.data,
                                celery_id=celery_id))
    _log.info("Rendering index page")

    return render_template("dashboard/index.html", form=form)


@bp.route("/output/<input_type>/<output_type>/<celery_id>", methods=['GET'])
def output(input_type, output_type, celery_id):
    return render_template("dashboard/output.html",
                           input_type=input_type,
                           output_type=output_type,
                           celery_id=celery_id)


@bp.route("/queue/", methods=['GET'])
def queue():
    return render_template("dashboard/queue.html")


@bp.errorhandler(Exception)
def exception_error_handler(error):  # pragma: no cover
    _log.exception(error)
    return render_template('dashboard/error.html', msg=error), 500


@bp.before_request
def before_request():
    g.xssp_version = get_version()

@bp.route('/support/', methods=['GET', 'POST'])
def support():
    form = SupportForm()

    if form.validate_on_submit():
        email = form.email.data
        body = form.body.data

        mail.send("Support Request", email,
                  [app.config["ADMINISTRATOR_EMAIL"]],
                   body)

        return render_template('dashboard/support_sent.html')

    return render_template('dashboard/support.html', form=form)

xssp_api/frontend/templates/api/docs.html
{% extends "base.html" %}

{% block content %}

{% for url, (method, doc) in docs.items()|sort %}
  <h3><samp>/api{{ url }}</samp> <small>({{ method }})</small></h3>
  {{ doc|beautify_docstring }}
  <hr>
{% endfor %}

{% endblock %}

{% block js %}
{% endblock %}

xssp_api/frontend/templates/api/examples.html
{% extends "base.html" %}

{% block content %}

<h2>API Examples</h2>
<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#python" data-toggle="tab">Python</a></li>
    <li><a href="#perl" data-toggle="tab">Perl</a></li>
  </ul>
  <div class="tab-content">
    <div id="python" class="tab-pane active">
      <br/>
      <p>
      This example generates HSSP data from the PDB data for 1CRN. The PDB data
      is sent to the server, which returns a job ID. This means that the server
      is currently processing the request. Every five seconds the status of the
      request is queried, and when it's success, the result is requested and
      printed to the console.
      </p>
      <pre>
<code class="python">
"""
This example client takes a PDB file, sends it to the REST service, which
creates HSSP data. The HSSP data is then output to the console.

Example:

    python pdb_to_hssp.py 1crn.pdb https://www3.cmbi.umcn.nl/xssp/
"""

import argparse
import json
import requests
import time


def pdb_to_hssp(pdb_file_path, rest_url):
    # Read the pdb file data into a variable
    files = {'file_': open(pdb_file_path, 'rb')}

    # Send a request to the server to create hssp data from the pdb file data.
    # If an error occurs, an exception is raised and the program exits. If the
    # request is successful, the id of the job running on the server is
    # returned.
    url_create = '{}api/create/pdb_file/hssp_hssp/'.format(rest_url)
    r = requests.post(url_create, files=files)
    r.raise_for_status()

    job_id = json.loads(r.text)['id']
    print "Job submitted successfully. Id is: '{}'".format(job_id)

    # Loop until the job running on the server has finished, either successfully
    # or due to an error.
    ready = False
    while not ready:
        # Check the status of the running job. If an error occurs an exception
        # is raised and the program exits. If the request is successful, the
        # status is returned.
        url_status = '{}api/status/pdb_file/hssp_hssp/{}/'.format(rest_url,
                                                                  job_id)
        r = requests.get(url_status)
        r.raise_for_status()

        status = json.loads(r.text)['status']
        print "Job status is: '{}'".format(status)

        # If the status equals SUCCESS, exit out of the loop by changing the
        # condition ready. This causes the code to drop into the `else` block
        # below.
        #
        # If the status equals either FAILURE or REVOKED, an exception is raised
        # containing the error message. The program exits.
        #
        # Otherwise, wait for five seconds and start at the beginning of the
        # loop again.
        if status == 'SUCCESS':
            ready = True
        elif status in ['FAILURE', 'REVOKED']:
            raise Exception(json.loads(r.text)['message'])
        else:
            time.sleep(5)
    else:
        # Requests the result of the job. If an error occurs an exception is
        # raised and the program exits. If the request is successful, the result
        # is returned.
        url_result = '{}api/result/pdb_file/hssp_hssp/{}/'.format(rest_url,
                                                                  job_id)
        r = requests.get(url_result)
        r.raise_for_status()
        result = json.loads(r.text)['result']

        # Return the result to the caller, which prints it to the screen.
        return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Create HSSP from a PDB file')
    parser.add_argument('pdb_file_path')
    parser.add_argument('rest_url')
    args = parser.parse_args()

    result = pdb_to_hssp(args.pdb_file_path, args.rest_url)
    print result
</code>
      </pre>
    </div>
    <div id="perl" class="tab-pane">
      <br/>
      <p>
      This example generates a DSSP file for 1CRN. The PDB data is sent to the
      server, which returns a job ID. This means that the server is currently
      processing the request. Every five seconds the status of the request is
      queried, and when it's success, the result is requested and a DSSP file
      is created.
      </p>
      <pre>
<code class="perl">
=begin
This example client takes a PDB file, sends it to the REST service that
creates the DSSP data, which is written to a DSSP file.

Example:

    perl pdb_to_dssp.pl 1crn.pdb 1crn.dssp
=cut


use strict;
use warnings;
use HTTP::Request::Common;
use LWP::UserAgent;
use JSON qw( decode_json );


my $url_xssp = "https://www3.cmbi.umcn.nl/xssp/";
my $ua = LWP::UserAgent->new;
my $input = shift;
my $output = shift;


die "Usage: pdb_to_dssp.pl <infile> <outfile>\n" unless defined $input and \
  defined $output;


# Sends a request to the server to create a dssp file from the pdb file data.
# If an error occurs the program exits.
my $url_create = $url_xssp . "api/create/pdb_file/dssp/";
my $response = $ua->request(POST $url_create,
  Content_Type => "multipart/form-data",
  Content => [
    file_ => [$input],
  ]);
die $response->status_line unless $response->is_success;


# If the request is successful, the id of the job running on the server is
# returned.
my $content = decode_json($response->content);
my $id = $content->{'id'};


# Loops unil the job running on the server has finished, either successfully
# or due to an error.
my $ready = 0;
until ($ready) {
  # Check the status of the running job.
  # If an error occurs the program exits.
  my $url_status = $url_xssp . "api/status/pdb_file/dssp/" . $id . "/";
  $response = $ua->request(GET $url_status);
  die $response->status_line unless $response->is_success;

  # If the request is successful, the status is returned.
  my $content = decode_json($response->content);
  my $status = $content->{'status'};
  print "Job status is: " . $status . "\n";

  if ($status eq 'SUCCESS') {
    $ready = 1;
  } elsif ($status eq 'FAILURE' or $status eq 'REVOKED') {
    die $status;
  } else {
    sleep 5;
  }
}


# Requests the result of the job. If an error occurs the program exits.
my $url_result = $url_xssp . "api/result/pdb_file/dssp/" . $id . "/";
$response = $ua->request(GET $url_result);
die $response->status_line unless $response->is_success;

$content = decode_json($response->content);
my $result = $content->{'result'};
open(my $g, ">$output") or die "Could not open output file: $!\n";
print $g $result;
close($g);
</code>
      </pre>
    </div>
  </div>
</div>


{% endblock %}

{% block js %}
<script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

xssp_api/frontend/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <!-- Matomo -->
    <script>
      var _paq = window._paq = window._paq || [];

      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */

      _paq.push(['trackPageView']);

      _paq.push(['enableLinkTracking']);

      (function() {

        var u="//www3.cmbi.umcn.nl/matomo/";

        _paq.push(['setTrackerUrl', u+'matomo.php']);

        _paq.push(['setSiteId', '4']);

        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];

        g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);

      })();
    </script>
    <!-- End Matomo Code -->

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <!-- Javascript -->
    <script src="{{ url_for('static',
                            filename='libs/jquery/dist/jquery.min.js') }}" type="text/javascript">
    </script>
    <script src="{{ url_for('static',
                            filename='libs/bootstrap/dist/js/bootstrap.min.js') }}" type="text/javascript">
    </script>
    <script src="{{ url_for('static',
                            filename='libs/bootstrap-tour/build/js/bootstrap-tour.js') }}" type="text/javascript">
    </script>
    <script src="{{ url_for('static',
                            filename='libs/highlightjs/highlight.pack.js') }}" type="text/javascript">
    </script>

    <!-- Stylesheets -->
    <link rel="stylesheet"
          href="{{ url_for('static',
                           filename='libs/bootstrap/dist/css/bootstrap.min.css') }}" type="text/css">

    <link rel="stylesheet"
          href="{{ url_for('static',
                           filename='libs/bootstrap-tour/build/css/bootstrap-tour.min.css') }}" type="text/css">

    <link rel="stylesheet"
          href="{{ url_for('static',
                           filename='libs/highlightjs/styles/github.css') }}" type="text/css">


    <link rel="stylesheet"
          href="{{ url_for('static',
                           filename='css/site.css') }}" type="text/css">
  </head>

  <body>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <!-- Navbar header -->
        <div class="navbar-header">
          <a class="navbar-brand logo" href="{{ url_for('dashboard.index') }}">
            <p>xssp</p>
          </a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a id="start_tour" href="#">Help</a>
          </li>
          <li>
            <a href="{{ url_for('dashboard.support') }}">Support</a>
          </li>
          <li>
            <a href="{{ url_for('xssp.api_doc') }}">API</a>
          </li>
          <li>
            <a href="{{ url_for('xssp.api_examples') }}">API Examples</a>
          </li>
        </ul>
      </div>
    </nav>

    <!-- Flashed messages -->
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <div class="container">
          <div class="alert alert-dismissable alert-success">
            <button type="button" class="close" data-dismiss="alert"
                    aria-hidden="true">&times;</button>
            {% for message in messages %}
              <p>{{ message }}</p>
            {% endfor %}
          </div>
        </div>
      {% endif %}
    {% endwith %}

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <footer class="footer">
      <div class="container navbar">
        <hr style='padding: 5px; margin: 0;'>
        <div class="row">
          <div class="col-sm-4 col-md-4 col-lg-4">
            <p class="pull-right" style='color: darkgray;'>
              Note: This website uses <a href="https://matomo.org/">Matomo</a> to analyze its usage.
            </p>
          </div>
          <div class="col-sm-2 col-md-2 col-lg-2">
            <p class="pull-left" style='color: lightgray;'>
            Version: {{ g.xssp_version }}
            </p>
          </div>
          <div class="col-sm-2 col-md-2 col-lg-2">
            <p class="pull-right">
              <a style='color: darkgray;'
               href="https://github.com/cmbi/xssp-api">
                Feedback
              </a>
            </p>
          </div>
          <div class="col-sm-2 col-md-2 col-lg-2">
            <p class="pull-left">
              <a style='color: darkgray;'
               href="http://swift.cmbi.umcn.nl/gv/facilities/facil_2.html">
                Citations
              </a>
            </p>
          </div>
          <div class="col-sm-2 col-md-2 col-lg-2">
            <p class="pull-right">
              <a style='color: lightgray;'
               href="http://swift.cmbi.umcn.nl/gv/facilities/">
                CMBI facilities
              </a>
            </p>
          </div>
        </div>
      </div>
    </footer>

    <script>
    $(document).ready(function() {
      $("#start_tour").click(function() {
        if (window.location.pathname != '/') {
          window.location.replace("{{ url_for('dashboard.index') }}" +
                                  "?tour=true");
        }
      });
    });
    </script>

    {% block js %}
    {% endblock %}
  </body>
</html>

xssp_api/frontend/templates/dashboard/error.html
{% extends "base.html" %}

{% block content %}

<h2>Error processing request</h2>
<hr>

<p class="lead">
  There was an error processing your request. This isn't your fault, it's ours.
  The system administrator has been notified and will address the issue as
  quickly as possible. The reason for the failure is:
</p>

<code class="red">{{ msg }}</code>

{% endblock %}

{% block js %}
{% endblock %}

xssp_api/frontend/templates/dashboard/index.html
{% extends "base.html" %}

{% block content %}

{% from "form_macros.html" import render_form_errors %}

{{ render_form_errors(form) }}

<form id="xssp_form" method="post" action="{{ url_for('dashboard.index') }}"
      role="form" enctype="multipart/form-data">
  {{ form.csrf_token }}

  <div class="row">
    <div class="col-xs-6">
      <div id="output_type_div" class="form-group">
        {{ form.output_type.label }}
        {{ form.output_type(class_='form-control') }}
      </div>
    </div>
    <div class="col-xs-6">
      <div id="input_type_div" class="form-group">
        {{ form.input_type.label }}
        {{ form.input_type(class_='form-control') }}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div id="pdb_id_div" class="form-group hidden">
        {{ form.pdb_id(class_='form-control',
                       placeholder='Enter a PDB code') }}
      </div>
      <div id="sequence_div" class="form-group hidden">
        {{ form.sequence(class_='form-control',
                         placeholder='Enter a protein sequence',
                         rows="3") }}
      </div>
      <div id="pdb_file_div" class="form-group hidden">
        <div class="input-group">
          <span class="input-group-btn">
            <span class="btn btn-primary btn-file">
              Browse&hellip; {{ form.file_(class='form-control') }}
            </span>
          </span>
          <input type="text" class="form-control" disabled>
        </div>
      </div>
    </div>
  </div>
  <hr/>
  <div id="form_submit_div" class="form-group pull-right">
    <button id="btn_clear" type="reset" class="btn btn-default">Clear</button>
    <button type="submit" class="btn btn-success">Submit</button>
  </div>
</form>

{% endblock %}

{% block js %}

<script type="text/javascript">
  function show_pdbid_input() {
    $('#pdb_id_div').removeClass('hidden');
    $('#sequence_div').addClass('hidden');
    $('#pdb_file_div').addClass('hidden');
  }

  function show_pdbfile_input() {
    $('#pdb_id_div').addClass('hidden');
    $('#sequence_div').addClass('hidden');
    $('#pdb_file_div').removeClass('hidden');
  }

  function show_sequence_input() {
    $('#pdb_id_div').addClass('hidden');
    $('#sequence_div').removeClass('hidden');
    $('#pdb_file_div').addClass('hidden');
  }

  function update_input_types() {
    var selected = $('#output_type').children(":selected").attr('value');
    switch (selected) {
      case 'dssp':
        $('#input_type').empty();
        $('#input_type').append('<option value="pdb_id">PDB Id</option>');
        $('#input_type').append('<option value="pdb_redo_id">PDB_REDO Id</option>');
        $('#input_type').append('<option value="pdb_file">PDB File</option>');
        break;
      case 'hssp_hssp':
        $('#input_type').empty();
        $('#input_type').append('<option value="pdb_id">PDB Id</option>');
        $('#input_type').append('<option value="pdb_file">PDB File</option>');
        $('#input_type').append('<option value="sequence">Sequence</option>');
        break;
      case 'hssp_stockholm':
        $('#input_type').empty();
        $('#input_type').append('<option value="pdb_id">PDB Id</option>');
        $('#input_type').append('<option value="pdb_file">PDB File</option>');
        $('#input_type').append('<option value="sequence">Sequence</option>');
        break;
      case 'hg_hssp':
        $('#input_type').empty();
        $('#input_type').append('<option value="sequence">Sequence</option>');
        break;
    }
    show_data_input();
  }

  function show_data_input() {
      var selected = $('#input_type').children(":selected").attr('value');
      switch (selected) {
      case 'pdb_id':
        show_pdbid_input();
        break;
      case 'pdb_redo_id':
        show_pdbid_input();
        break;
      case 'pdb_file':
        show_pdbfile_input();
        break;
      case 'sequence':
        show_sequence_input();
        break;
      }
  }

  function show_tour_data_input(index) {
      switch (index) {
      case 3:
        show_pdbid_input();
        break;
      case 4:
        show_pdbfile_input();
        break;
      case 5:
        show_sequence_input();
        break;
      }
  }

  function get_query_param(param) {
    var result =  window.location.search.match(
        new RegExp("(\\?|&)" + param + "(\\[\\])?=([^&]*)"));
    return result ? result[3] : false;
  }

  $(document).on('change', '.btn-file :file', function() {
    var input = $(this),
        numFiles = input.get(0).files ? input.get(0).files.length : 1,
        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);
  });

  $(document).ready( function() {
    $('.btn-file :file').on('fileselect', function(event, numFiles, label) {
          var input = $(this).parents('.input-group').find(':text'),
              log = numFiles > 1 ? numFiles + ' files selected' : label;

          if( input.length ) {
              input.val(log);
          } else {
              if( log ) alert(log);
          }
    });

    // Setup tour
    var tour = new Tour({
      backdrop: true,
      orphan: true,
      storage: false,
      onNext: function (tour) {
        show_tour_data_input(tour.getCurrentStep() + 1)
      },
      onPrev: function (tour) {
        show_tour_data_input(tour.getCurrentStep() - 1)
      },
      onEnd: function (tour) { show_data_input(); },
      steps: [
      {
        element: "",
        title: "Start Tour",
        content: "Welcome to XSSP. This tour explains the usage of XSSP." +
                 " Once the tour is complete, you can get started!" +
                 "<br><br>Click next to begin."
      },
      {
        element: "#output_type_div",
        title: "Output Type",
        content: "Select the output generated by XSSP."
      },
      {
        element: "#input_type_div",
        title: "Input Type",
        content: "Select the type of protein data you will provide." +
                 "<br><br>Each option will change the input form to provide " +
                 "an appropriate form control." +
                 "<br><br>PDB_REDO ids correspond to fully optimised PDB_REDO " +
                 "structure models."
      },
      {
        element: "#pdb_id_div",
        title: "PDB Identifier",
        content: "For the PDB id input type, enter a Protein Data Bank code. " +
                 "For example: 1CRN"
      },
      {
        element: "#pdb_file_div",
        title: "PDB File",
        content: "For the PDB file input type, click the " +
                 "<code>Browse...</code> button and select the PDB file to " +
                 "upload." +
                 "<br><br>PDB files are accepted in both PDB format and " +
                 "mmCIF format. Additionally, compressed .gz and .bz2 files" +
                 " can be uploaded."
      },
      {
        element: "#sequence_div",
        title: "Sequence",
        content: 'For the sequence input type, enter the protein sequence ' +
                 'using the 1-letter codes of the 20 canonical amino acids. ' +
                 'The sequence must be at least 25 residues long. ' +
                 'FASTA format is allowed.'
      },
      {
        element: "#form_submit_div",
        title: "Submit",
        content: "When you're ready, click <code>Submit</code> to send your " +
                 "request to the server.<br><br>A result page will be shown " +
                 "with the status of your request, and when completed, the " +
                 "output will be shown."
      }
    ]});
    tour.init();

    // Start the tour automatically if redirected to the index page via the
    // help button.
    if (get_query_param('tour')) {
      tour.restart();
    }

    $('#start_tour').click(function() { tour.restart(); });

    // Show the correct input widget depending on the selected input method.
    $('#input_type').change(function() { show_data_input(); });

    // Update the input type selection list to exclude invalid combinations.
    $('#output_type').change(update_input_types);

    // Ensure that the correct input field is displayed when the form reloads
    // due to form errors, page refreshing, or the back button.
    $('#input_type').trigger('change');

    // Ensure the correct input field is displayed when the form is cleared.
    $('#btn_clear').click(function() { $('#xssp_form')[0].reset();
      show_data_input();
    });

    // Ensure that the input types listed are correct for the selected output
    // type.
    var selected = $('#input_type').children(":selected").attr('value');
    update_input_types();
    $('#input_type option[value=' + selected + ']').prop('selected', true);
  });
</script>

{% endblock %}

xssp_api/frontend/templates/dashboard/output.html
{% extends "base.html" %}

{% block content %}

<div class="panel panel-default">
  <div class="panel-heading">Result</div>
  <div class="panel-body">
    <p>
      Please wait while your request is processed. This can take a long time.
      The status of your request is shown below.
    </p>
    <div class="form-group">
      <span class="label label-default" id="status">QUEUED</span>
    </div>
    <textarea class="form-control" id="output"
              style="font-family: monospace; font-size: 8pt;"
              rows=30 readonly>
    </textarea>
    <a id="download" class="btn btn-default">Download</a>
    <br>
    <p>
      Doing this often? Consider using the
      <a href='{{ url_for('xssp.api_doc') }}'>API</a> to automate the process.
      Check out the <a href='{{ url_for('xssp.api_examples') }}'>simple
      ready-to-use examples</a>.
    </p>
    <p>
      Instructions for downloading existing DSSP files using rsync can be found
      <a href="http://swift.cmbi.umcn.nl/gv/dssp">here</a>.
    </p>
  </div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
  $(document).ready(function() {
      function _get_status_class(status) {
        if (status == 'PENDING') {
          return 'label-default';
        } else if (status == 'STARTED') {
          return 'label-primary';
        } else if (status == 'FAILURE') {
          return 'label-danger';
        } else if (status == 'SUCCESS') {
          return 'label-success';
        }
      }

      var intervalId = setInterval(update_status, 10000);

      update_status();

      function update_status() {
        $.getJSON(
          "{{ url_for('xssp.get_xssp_status', input_type=input_type, output_type=output_type, id=celery_id) }}",
          function(data) {
            // Remove all classes from the status message
            $('#status').removeClass();

            // Set the status text and classes
            $('#status').text(data['status']);
            var status_class = _get_status_class(data['status']);
            $('#status').addClass("label " + status_class);

            if (data['status'] == 'FAILURE') {
              clearInterval(intervalId);
              $('#output').text(data['message']);
            }

            if (data['status'] == 'SUCCESS') {
              clearInterval(intervalId);
              $.getJSON(
                  "{{ url_for('xssp.get_xssp_result', input_type=input_type, output_type=output_type, id=celery_id) }}",
                function(data) {
                  $('#output').text(data['result']);

                  $('#download').attr('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(data['result']));
                  $('#download').attr('download', '{{ celery_id }}.{{ output_type }}');
              });
            }
          }
        )
      }
  });
</script>
{% endblock %}

xssp_api/frontend/templates/dashboard/support.html
{% extends "base.html" %}

{% from "form_macros.html" import render_form_errors %}

{{ render_form_errors(form) }}

{% block content %}
<div class="panel panel-default">
    <div class="panel-body">
        <h3>Get in touch with us</h3>
        <p>
            Please include the following information if your query is about an xssp job.
            <ul>
                <li>URL of the job if available</li>
                <li>The input data and the expected output</li>
                <li>A description of the problem</li>
                <li>Your expectation</li>
            </ul>
        </p>
        <hr>
        <form id="support_form" method="post"
              action="{{ url_for('dashboard.support') }}"
              role="form" enctype="multipart/form-data">
            {{ form.hidden_tag() }}

            <div class="row">
                <div class="col-xs-12">
                    {{ form.email(class_='form-control',
                                  placeholder='Email address') }}
                </div>
            </div>
            <div class="row" style="margin-top: 10px;">
                <div class="col-xs-12">
                    {{ form.body(class_='form-control', placeholder='Message',
                                 rows='10') }}
                </div>
            </div>
            <hr>
            <div id="form_submit_div" class="form-group pull-right">
                <button type="submit" class="btn btn-success">Send</button>
            </div>
            <div>
              {% for field_name, errors in form.errors.items() %}
                {% for error in errors %}
                  <code class="red">{{ error }}</code>
                {% endfor %}
              {% endfor %}
            </div>
        </form>
    </div>
</div>
{% endblock %}

xssp_api/frontend/templates/dashboard/support_sent.html
{% extends "base.html" %}

{% from "form_macros.html" import render_form_errors %}

{{ render_form_errors(form) }}

{% block content %}
<div class="panel panel-default">
    <div class="panel-body">
        <h3>Thanks for getting in touch</h3>
        <p>
            We'll be in touch as soon as possible.
        </p>
    </div>
</div>
{% endblock %}